### ISSUE TITLE
invalid deployment target for -stdlib=libc++ (requires OS X 10.7 or later)

### ISSUE THREAD

**Issue by jBachalo** [bakercp/ofxTime#2]
Trying to compile the example using latest Ofx 0.9 targeting the latest OSX SDK 10.11 and get the following error

invalid deployment target for -stdlib=libc++ (requires OS X 10.7 or later)

Anyone have an idea how I might resolve?

**Comment by jBachalo** [comment]
issue resolved. was targeting 10.6 in Build Settings > >Deployment

**Comment by bakercp** [comment]
Did you regenerate your project files with the new project generator?

**Comment by bakercp** [comment]
Ah super!

**Comment by jBachalo** [comment]
however getting 2 other errors in CalendarWidget.cpp  Ofx 0.9 related?? :( posting separate issue

**Comment by bakercp** [comment]
Also, not to downplay the usefulness of this library, but with the adoption of c++11 in openFrameworks 0.9+ there are a lot of new fancy time / date features that would be worth checking out.

**Comment by jBachalo** [comment]
thanks
